# Site settings
title: Machine Learning Fish
email: baris@machinelearningfish.com
description: > # this means to ignore newlines until "baseurl:"
  A fun introduction to machine learning. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://machinelearningfish.com" # the base hostname & protocol for your site
twitter_username: baris_wonders
github_username:  byuksel

# Build settings
markdown: kramdown

